"""
Base classes for strategy implementations.
"""

import logging
from abc import ABC
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional

logger = logging.getLogger(__name__)


class Signal(Enum):
    """Trading signals generated by strategies."""

    LONG = "LONG"
    SHORT = "SHORT"
    CLOSE = "CLOSE"
    HOLD = "HOLD"


@dataclass
class TradeSignal:
    """
    Container for a trading signal generated by a strategy.

    Attributes:
        signal: The type of signal (LONG, SHORT, CLOSE, HOLD)
        entry_price: The price at which to enter the trade (for LONG/SHORT signals)
        take_profit: The price at which to take profit (optional)
        stop_loss: The price at which to stop loss (optional)
        reason: A string describing the reason for the signal
        metadata: Dictionary containing state information (e.g., indicators, session name,
                  range levels) for debugging and audit trails.
    """

    signal: Signal
    entry_price: float = 0.0
    take_profit: Optional[float] = None
    stop_loss: Optional[float] = None
    reason: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def is_entry(self) -> bool:
        """Check if signal is an entry signal."""
        return self.signal in (Signal.LONG, Signal.SHORT)

    @property
    def is_exit(self) -> bool:
        """Check if signal is an exit signal."""
        return self.signal == Signal.CLOSE

    @property
    def is_long(self) -> bool:
        """Check if signal is a long entry."""
        return self.signal == Signal.LONG

    @property
    def is_short(self) -> bool:
        """Check if signal is a short entry."""
        return self.signal == Signal.SHORT

    def __repr__(self) -> str:
        tp_str = f"{self.take_profit:.2f}" if self.take_profit is not None else "None"
        sl_str = f"{self.stop_loss:.2f}" if self.stop_loss is not None else "None"

        return (
            f"TradeSignal({self.signal.value}, "
            f"entry={self.entry_price:.2f}, "
            f"tp={tp_str}, sl={sl_str})"
        )


class Strategy(ABC):
    """
    Abstract base class for trading strategies.

    Subclasses must implement the generate_signal method which
    processes market data and returns trading signals.
    """

    def __init__(self, name: str = "BaseStrategy"):
        """
        Initialize the strategy with a name and an empty parameters dictionary.

        Args:
            name: Strategy name for identification
        """
        self.name = name
        self._params: Dict[str, Any] = {}
        logger.info("Initialized strategy: %s", name)

    @property
    def params(self) -> Dict[str, Any]:
        """Get strategy parameters."""
        return self._params

    @params.setter
    def params(self, value: Dict[str, Any]) -> None:
        """Set strategy parameters."""
        self._params = value

    def generate_signal(
        self,
        bar: Dict[str, Any],
        current_position: Optional[Any] = None,
        is_warmup: bool = False,
    ) -> TradeSignal:
        """
        Generate a trading signal based on the provided market data.

        Args:
            bar: Current market data bar (Dict). Should contain OHLCV and required indicators.
            current_position: The `Position` object from the trading engine, if any.
            is_warmup: Flag used during historical data injection (cold start).
                       - If True: Strategy should update internal indicators/state (e.g.,
                                  opening range boundaries, VWAP anchors) but MUST NOT
                                  trigger new entries or increment trade counters.
                       - If False: Normal live/backtest operation.
        """
        pass

    def validate_bar(
        self,
        bar: Dict[str, Any],
        required_fields: List[str] = [],
    ) -> bool:
        """
        Validate the incoming market data bar.

        Args:
            bar: A dictionary containing market data (e.g., price, volume)
            required_fields: A list of required fields that must be present in the bar

        Returns:
            True if the bar is valid, False otherwise
        """
        missing = [field for field in required_fields if field not in bar]
        if missing:
            logger.warning("Bar is missing required fields: %s", missing)
            return False

        return True

    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name={self.name})"
