"""
Base classes for strategy implementations.
"""

from abc import ABC, abstractmethod
from dataclasses import field
from enum import Enum
import logging
from typing import Any, Dict, List, Optional

from attr import dataclass

logger = logging.getLogger(__name__)

class Signal(Enum):
    """Trading signals generated by strategies."""

    LONG = "LONG"
    SHORT = "SHORT"
    CLOSE = "CLOSE"
    HOLD = "HOLD"

@dataclass
class TradeSignal:
    """
    Container for a trading signal generated by a strategy.

    Attributes:
    """

    signal: Signal
    entry_price: float = 0.0
    take_profit: float = 0.0
    stop_loss: float = 0.0
    reason: str = ""
    metadata: Dict[str, Any] = field(default_factory=dict)

    @property
    def is_entry(self) -> bool:
        """Check if signal is an entry signal."""
        return self.signal in (Signal.LONG, Signal.SHORT)

    @property
    def is_exit(self) -> bool:
        """Check if signal is an exit signal."""
        return self.signal == Signal.CLOSE

    @property
    def is_long(self) -> bool:
        """Check if signal is a long entry."""
        return self.signal == Signal.LONG

    @property
    def is_short(self) -> bool:
        """Check if signal is a short entry."""
        return self.signal == Signal.SHORT

    def __repr__(self) -> str:
        return (
            f"TradeSignal({self.signal.value}, "
            f"entry={self.entry_price:.2f}, "
            f"tp={self.take_profit:.2f}, "
            f"sl={self.stop_loss:.2f})"
        )
    
class Strategy(ABC):
    """
    Abstract base class for trading strategies.

    Subclasses must implement the generate_signal method which
    processes market data and returns trading signals.
    """

    def __init__(self, name: str = "BaseStrategy"):
        """
        Initialize the strategy with a name and an empty parameters dictionary.

        Args:
            name: Strategy name for identification
        """
        self.name = name
        self._params: Dict[str, Any] = {}
        logger.info("Initialized strategy: %s", name)

    @property
    def params(self) -> Dict[str, Any]:
        """Get strategy parameters."""
        return self._params

    @params.setter
    def params(self, value: Dict[str, Any]) -> None:
        """Set strategy parameters."""
        self._params = value

    @abstractmethod
    def generate_signal(
        self,
        bar: Dict[str, Any],
        current_position: Optional[Any] = None
    ) -> TradeSignal:
        """
        Generate a trading signal based on the provided market data.

        Args:
            bar: A dictionary containing market data (e.g., price, volume)
            current_position: Optional information about the current position
        """
        pass

    def validate_bar(
        self,
        bar: Dict[str, Any],
        required_fields: List[str] = []
    ) -> bool:
        """
        Validate the incoming market data bar.

        Args:
            bar: A dictionary containing market data (e.g., price, volume)
            required_fields: A list of required fields that must be present in the bar

        Returns:
            True if the bar is valid, False otherwise
        """
        missing = [field for field in required_fields if field not in bar]
        if missing:
            logger.warning("Bar is missing required fields: %s", missing)
            return False

        return True
    
    def __repr__(self) -> str:
        return f"{self.__class__.__name__}(name={self.name})"